### ISSUE TITLE
圣遗物识别相关建议

### ISSUE THREAD

**Issue by zyr17** [ChanIok/JumpyDumpty#2]
感谢大佬的工具！
我目前用基于 https://github.com/kyloris0660/GenshinArtifactRecorder 的魔改来拉取圣遗物信息，
使用AutoHotKey和Python导出Excel的方式。在遗物识别流程中有一些处理思路想和您讨论一下看看是否有可能加入？

1. 我现在使用了AutoHotKey截取圣遗物界面。输入背包圣遗物数量，脚本会自动依次点击圣遗物，然后将截图保存在本地。
如果在Electron中实现，需要程序能够获取原神窗口位置并模拟鼠标；或是将AutoHotKey作为外部可执行文件/脚本集成。
不知道Electron能否做到类似的操作？我简单查找了一下robotjs可能可以控制鼠标，获取游戏窗口位置可能得通过WinAPI。
只不过也可以将游戏全屏避开查找窗口位置的问题。
2. 当前不会识别圣遗物的星数和强化等级，我自己当时导出圣遗物的一个主要目的是辅助选择强哪些胚子用的，
因此会关心星数和等级。因为百度识图不够靠谱（1920x1080，无法直接识别到+4等级），我的脚本截的圣遗物图面板位置完全相同，所以星级我是直接像素颜色比对的，等级我发现把它从图上抠下来再识别就能被识别出来。不知道这方面您是否有加入的想法和方式？
3. 关于识图数字不准，我的处理思路是：主词条除了花羽和精通全部都是百分比；副词条爆爆充肯定是百分比；如果字符串倒数第二个是`.`，说明丢了百分号肯定是百分比；带了百分号肯定是百分比。然后移除字符串中所有的`. , %`，百分比的必定一位小数否则就是整数。这样基本上不需要考虑小数点的问题，有可能弄错的只有条目名称出错（我还没碰到过）；副词的攻防生，且出错条件是 1) 数字条刚好倒数第二位多了个点 2) 百分比条的百分号和点都丢了。这两个条件都蛮难的，如果您觉得可行我可以把我的Python版本翻译成js。

附件是我现在用的ahk脚本和几个相关python函数。
[artifact.zip](https://github.com/ChanIok/JumpyDumpty/files/6026494/artifact.zip)

**Comment by ChanIok** [comment]
感谢大佬的建议！
其实我很菜的，我有些不太懂的地方
1.AutoHotKey我不是很了解，能否说下您目前的程序是怎么获取要点击的圣遗物坐标，另外在不同分别率的情况下你的方案可以正常运行吗。实测过robotjs的确可以控制鼠标，但位置好像不好处理，似乎不能根据窗口句柄来点击窗口的某个坐标。electron倒是可以执行exe的。
2.这种分析方案很好，后面我也打算处理的
3.目前的程序也是大致按照这种思路处理数据的，在我的背包测试过基本都没问题，不过放到论坛上就有人出问题了....这方面感谢您提供的解决方案

**Comment by zyr17** [comment]
我自己是1920x1080窗口模式的，AutoHotKey自己有接口查询当前活跃的窗口、大小和位置，所以比较方便。别的分辨率现在不能工作，因为本来就是自用脚本就没想这么多，直接写死了坐标。

如果是调用脚本来截图的话，我得改造下脚本去支持不同分辨率。比较恶心的是，窗口模式下画面是1920*1080的但是不同系统下边框大小不同，导致不方便精确对齐坐标，我得找找方法确认真实画面坐标，然后调下我现在记录的坐标。

如果用全屏模式的话会比较方便，直接以1080P的分辨率坐标做缩放可能就可以了。robotjs对于全屏游戏能控制鼠标和截取屏幕么？可以的话可以做成electron原生的，就不用外挂别的东西了。

另外一个难点是圣遗物要翻页，这个我没有在其他电脑上测试，自己电脑上发现我的自动滚动会有一点误差没法滚得很准，大概滚100行就有明显误差了（但是最多也就140行，所以我自用没有影响）。可能需要考虑怎么提升稳定性。感觉真的要实装还有不少需要改的地方，现在只能算是可行性探讨。。

第三个我翻译成js了，但是不怎么写js不知道有没有啥bug。。如果有用自取
```javascript
// name为词条名，value为数值，position主词条为圣遗物部位副词条为空。均为字符串
function stat_number_finetune(name, value, position){
    let always_v = [
        '生之花生命值', '死之羽攻击力', '空之杯元素精通', '理之冠元素精通',
        '时之沙元素精通', '元素精通',
    ];
    let always_p = [
        '空之杯生命值', '理之冠生命值', '时之沙生命值', '空之杯攻击力',
        '理之冠攻击力', '时之沙攻击力', '空之杯防御力', '理之冠防御力',
        '时之沙防御力', '时之沙元素充能效率', '理之冠治疗加成', '理之冠暴击率',
        '理之冠暴击伤害', '空之杯风元素伤害加成', '空之杯火元素伤害加成',
        '空之杯水元素伤害加成', '空之杯雷元素伤害加成', '空之杯冰元素伤害加成',
        '空之杯岩元素伤害加成', '空之杯物理伤害加成', '元素充能效率', '暴击率', 
        '暴击伤害'
    ];
    let l = value.length;
    if (l == 0) throw "value length zero";
    let ispercent = value[l - 1] == '%' || (l > 1 && value[l - 2] == '.');
    if (always_v.includes(position + name)) ispercent = false;
    if (always_p.includes(position + name)) ispercent = true;
    value = value.replace(/[,.%]/g, '');
    if (ispercent)
        return value.slice(0, value.length - 1) + '.' + value[value.length - 1] + '%';
    return value
}
```

**Comment by ChanIok** [comment]
对于同一种比例的确可以缩放坐标来点击。
16：9屏幕虽然比较典型，但也有不少人是用16:10甚至21：9这样的屏幕，那这种方案就难以起效了
[yllhwa大佬的项目](https://github.com/yllhwa/GenshinSpider)虽然停了，但他目前转向图像识别方案，正在做自动点击
如果依靠识别背包圣遗物图像获取位置来实现自动点击，效果会好很多，可以期待。
其实目前OCR数据处理结果收到的反馈比较少，应该还算稳定，我测试过自己背包的所有四五星圣遗物都准确录入。
在这方面很感谢您的宝贵意见！！

**Comment by yllhwa** [comment]
目前的进展：
对抓取的图像做灰度二值化后寻找轮廓，再拟合矩形轮廓
保留宽高比约为3的矩形基本上就是目标了，目前还在微调以获得更好效果
![ok](https://user-images.githubusercontent.com/42028599/108928943-095d5300-767e-11eb-824e-0776f3285c96.jpg)

测试代码：
```python
import cv2
import numpy as np

img = cv2.imread('./test3.jpg')

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # 灰度
ret, thresh = cv2.threshold(imgray, 198, 255, 0)  # 二值化
cv2.namedWindow("show", 0)
cv2.imshow('show', thresh)
cv2.waitKey(0)
contours, hierarchy = cv2.findContours(
    thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
    if (w < 110 or w > 130):
        continue
    if (h < 40 or h > 55):
        continue
    if (w / h >= 2 and w / h <= 4):
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 5)
        print((x, y), (w, h))

cv2.namedWindow("show", 0)
cv2.imshow('show', img)
cv2.waitKey(0)

```

**Comment by yllhwa** [comment]
# 自动识别点击的理论验证：
### 先上图(一共对9张不同分辨率图片进行了测试，此处选取两张)：
![test1](https://user-images.githubusercontent.com/42028599/108974970-f8820100-76c0-11eb-8be3-d8271df709ac.jpg)
![test1_ok](https://user-images.githubusercontent.com/42028599/108974984-fc158800-76c0-11eb-8134-6b342c8de5a9.jpg)
![test2](https://user-images.githubusercontent.com/42028599/108976941-059fef80-76c3-11eb-9190-bc0df7372437.jpg)
![test2_ok](https://user-images.githubusercontent.com/42028599/108976963-0c2e6700-76c3-11eb-98b4-a91c95aa660a.jpg)

# 思路:
### 1. 对图像简单的灰度处理，二值化。  
二值化的阈值经过我的实验大概在225比较好，背景产生的干扰最小。  
### 2. 初筛选矩形  
用opencv函数findContours查找轮廓，再用函数boundingRect拟合矩形，得到大量矩形轮廓。  
剔除其中宽高太小的，然后保留宽高比约为3的矩形  
### 3.  整理矩形  
用矩形的y坐标为依据将其分行  
### 4. 获取边界信息  
用投票的方法(我取的名字，其实就是求中位数)得到左右上下边界，由此得到间距。同时统计矩形平均的宽高。由以上信息可以画出完整的方阵(自己画而不是只看识别的，避免遗漏)。
### 5. 返回要点击的点  
通过上述信息返回要点击的点
# 翻页思路：
利用上述返回的点击信息(包含行信息)把最后一行移动到第一行，再次请求，此次把第二行移动到第一行，至此完成翻页操作。
# 整合建议
因为我不会用electron，所以用python进行了验证，不过如果electron方便使用opencv库的话很容易移植。如果不方便使用则可以考虑用electron调用python程序等方法。

# 程序:

```python
import cv2
import numpy as np
import math


def pre_treat(img):
    imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # 灰度
    ret, thresh = cv2.threshold(imgray, 225, 255, 0)  # 二值化
    return thresh


def test_show(img):
    cv2.namedWindow("show", 0)
    cv2.imshow('show', img)
    cv2.waitKey(0)


def pre_screen(contours):
    target = []  # 保存预筛选矩形
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)  # 拟合矩形轮廓
        # 剔除太小的矩形
        if (w < 80):
            continue
        if (h < 35):
            continue
        #cv2.rectangle(img, (x, y), (x + w, y + h), (255, 255, 0), 5)
        # 保留宽高比约为3的矩形到target
        if (w / h >= 2 and w / h <= 4):
            target.append({'x': x, 'y': y, 'w': w, 'h': h})
    return target


def arrange(target):
    detail = []  # 保存确定的矩形
    row = []  # 保存每一行

    # 将矩形结果分行
    row.append(target[-1])
    for item in target[-2::-1]:
        if abs(item['y'] - row[-1]['y']) < 50:
            row.append(item)
        else:
            detail.append([x for x in row])
            row.clear()
            row.append(item)
    if not row in detail:
        detail.append([x for x in row])

    # 剔除内容不足三个的行
    for row in detail[:]:
        if len(row) < 3:
            detail.remove(row)
    return detail


def get_border(detail):
    # 投票(取中位数)左边界\右边界\上边界\下边界
    left_x_list = []
    right_x_list = []
    up_y_list = []
    bottom_y_list = []
    for item in detail[0]:
        up_y_list.append(item['y'])
    for item in detail[-1]:
        bottom_y_list.append(item['y'])
    for row in detail:
        row.sort(key=(lambda item: item['x']))
        left_x_list.append(row[0]['x'])
        right_x_list.append(row[-1]['x'])
    left_x_list.sort()
    left_x = left_x_list[len(left_x_list) // 2]
    right_x_list.sort()
    right_x = right_x_list[len(right_x_list) // 2]
    up_y_list.sort()
    up_y = up_y_list[len(up_y_list) // 2]
    bottom_y_list.sort()
    bottom_y = bottom_y_list[len(bottom_y_list) // 2]
    return left_x, right_x, up_y, bottom_y


def process(img):
    thresh = pre_treat(img)  # 预处理
    contours, hierarchy = cv2.findContours(
        thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)  # 寻找轮廓
    target = pre_screen(contours)  # 初筛选矩形
    detail = arrange(target)  # 整理矩形，分行、剔除不合理内容
    left_x, right_x, up_y, bottom_y = get_border(detail)  # 划分边界
    # 计算每个的间隔
    aver_x = (right_x - left_x) / 6  # 7个圣遗物6个空格
    aver_y = (bottom_y - up_y) / (len(detail) - 1)
    # 统计矩形的平均宽高
    aver_w = detail[0][0]['w']
    aver_h = detail[0][0]['h']
    all_count = 0
    for row in detail:
        for item in row:
            aver_w += item['w']
            aver_h += item['h']
            all_count += 1
    aver_w /= all_count
    aver_h /= all_count

    out_detail = []
    test_img = img
    # 画出矩形
    for row in range(0, len(detail)):
        out_row = []
        for item in range(0, 7):
            out_row.append({'x': int(left_x+aver_x*item+aver_w/2),
                            'y': int(up_y+aver_y*row)})
            #cv2.rectangle(test_img, (int(left_x+aver_x*item), int(up_y+aver_y*row)), (int(left_x + aver_x * item + aver_w), int(up_y + aver_y * row + aver_h)), (0, 255, 0), 5)
        out_detail.append(out_row)
    return out_detail


def test():
    img = cv2.imread('./test7.png')  # 传入图片
    detail = process(img)
    for row in detail:
        for item in row:
            cv2.circle(img, (item['x'], item['y']), 20, (0, 0, 255), -1)
    test_show(img)
    cv2.imwrite('./test7_ok.png', img)


if __name__ == "__main__":
    test()

```

**Comment by ChanIok** [comment]
那看来目前理论上是可以实现自动点击了
[opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs#usage-with-electron)
[robotjs](https://github.com/octalmage/robotjs)
利用opencv4nodejs和robotjs，只是编译时不知道会不会出现各种问题，当初调用node的原生模块因为编译和打包折腾我大半天

**Comment by zyr17** [comment]
关于翻页，最后一页会滚不上去所以需要知道总共有多少圣遗物，每行每列有多少个，不然会重复。我自己的脚本需要手工输入圣遗物数量，然后选一行换一行直到剩余的圣遗物全部都展示了。
可能可以通过直接画面右上角区域的识图获取圣遗物数量，然后一页识别统计识别到的数量来自动化实现？

我自己用脚本自动滚动的时候出现了圣遗物行间距170但是需要鼠标移动180的情况，我不确定是什么原因引起的，这里也可能需要微调。

**Comment by zyr17** [comment]
yllhwa大佬的代码已经能够找出圣遗物行列数了，我没认真看。。基于`process`函数返回的detail坐标，我写了个识别圣遗物总数的函数。但是识别成功率感觉不是很稳定，“圣遗物xxx/1000”字样里面的`/`和`1`都有可能漏识别，不论高精还是普通OCR

另外，我自己测试在游戏分辨率宽度小于等于1400时由于每个圣遗物识别矩形的宽度和高度太小，全都没法识别。但是直接把阈值改小的话，在2k分辨率甚至1080P就会有文字部分的额外的框，导致行列识别错误。在不知道游戏框的分辨率的情况下暂时没想到怎么简单的解决

```python
def image_to_base64(img_np):
    image = cv2.imencode('.jpg', img_np)[1].tostring()
    return base64.b64encode(image)

def ocr_api(img, access_token):
    img = image_to_base64(img)
    params = {"image": img}
    request_url_high = "https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic"
    request_url = request_url_high + "?access_token=" + access_token
    headers = {'content-type': 'application/x-www-form-urlencoded'}
    response = requests.post(request_url, data=params, headers=headers)
    if response:
        # print(response.json())
        result = response.json()['words_result']
        return result
    raise ValueError

# 图片矩阵，process函数结果，access_token
def get_artifact_number(img, detail, access_token):
    # 通过矩阵得到右上角坐标和一个圣遗物的长宽
    dtop = detail[0][0]['y']
    dright = detail[0][-1]['x']
    height = (detail[1][0]['y'] - detail[0][0]['y'])
    width = (detail[0][1]['x'] - detail[0][0]['x'])
    # 根据坐标和长宽划定圣遗物字样所在图片范围，识别
    x1 = int(dright + 3 * width)
    y1 = int(dtop - 2 * height)
    x2 = int(x1 + 2 * width)
    y2 = int(y1 + 1.5 * height)
    x1 = max(x1, 0)
    y1 = max(y1, 0)
    print(x1, y1, x2, y2, img.shape)
    part_img = img[y1:y2, x1:x2]
    words = ocr_api(part_img, access_token)
    word = ''
    # 识别到的文字中匹配正则的
    for w in words:
        if re.match(r'^圣遗物(\d+?)/?1?000', w['words']):
            word = w['words']
    assert '圣遗物' in word
    # OCR可能会将`/1000`识别成`1000`或`/000`。不排除识别成`000`的情况，此时如果圣遗物
    # 个位数为1会出错（241/1000识别成241000，正则结果为24）。如果错误率太高还是得手动修正
    m = re.match(r'^圣遗物(\d+?)/?1?000', word)
    if m:
        print(m.group(1))
        return int(m.group(1))
    raise ValueError
```


测试用图 [test_imgs.zip](https://github.com/ChanIok/JumpyDumpty/files/6040347/test_imgs.zip)

**Comment by yllhwa** [comment]
@zyr17 阈值是可以动态获取的，这里给出的225只是经验上的感受，等我研究一下怎么获取。
另外如果证实可行的话可以用cv的方法来代替ocr，目前相关的研究仍在进行。
[我仓库CV相关的部分](https://github.com/yllhwa/GenshinSpider/tree/main/CV)会继续更新😄

**Comment by Live4dreamCH** [comment]
看得我也想参与了。。。不过我只有一点点cv基础

**Comment by yllhwa** [comment]
@Live4dreamCH 我是现学现卖的哈哈😂

**Comment by zyr17** [comment]
@Live4dreamCH 欢迎大佬加入，我对图形学也不怎么懂，都是摸索着搞的_(:3」∠)_

**Comment by Live4dreamCH** [comment]
请问目前版本的截屏，是全屏截图；还是可以通过句柄/窗口名之类的信息，直接截取到原神的窗口内容吗？
另外目前版本的程序里，有使用了任何图像处理的方法吗？如果没有，那是不是就是直接把一整张图片送到百度OCR的api里面，然后再从返回的文字中挑选出圣遗物相关的文字呢？
抱歉不太会js，只好在这里问。。。

**Comment by Live4dreamCH** [comment]
小有进展（指花了几天疯狂自学，差不多赶上了之前 @yllhwa 的进度，并做了一点点改进）
![rectangle_safe](https://user-images.githubusercontent.com/56406410/109408910-fec9f300-79c8-11eb-95e8-49e5d035399d.png)

**Comment by ChanIok** [comment]
> 请问目前版本的截屏，是全屏截图；还是可以通过句柄/窗口名之类的信息，直接截取到原神的窗口内容吗？
> 另外目前版本的程序里，有使用了任何图像处理的方法吗？如果没有，那是不是就是直接把一整张图片送到百度OCR的api里面，然后再从返回的文字中挑选出圣遗物相关的文字呢？
> 抱歉不太会js，只好在这里问。。。

@Live4dreamCH 
都是大佬，自学都那么快

目前版本是调用C++的windows库获取句柄，基于MFC的截屏，直接截取原神的窗口内容。这部分内容按照比例只保留圣遗物属性那片区域，没有采用任何图像处理的方法，直接丢给百度识别，然后返回对数据进行挑选，就是如此~

**Comment by Live4dreamCH** [comment]
> 这部分内容按照比例只保留圣遗物属性那片区域

我找到一个带鱼屏, 它有非常奇怪的分辨率比例, 请问这种方法在这样的图片上还能奏效吗?
![1920_540](https://user-images.githubusercontent.com/56406410/109409076-5d43a100-79ca-11eb-85be-860104f440de.png)

哦，我忘记了分辨率要求。。。sorry

**Comment by ChanIok** [comment]
![image](https://user-images.githubusercontent.com/10853091/109409125-f377c700-79ca-11eb-8b98-4d094b0b93b3.png)
 @Live4dreamCH 
没事，新版本是开放了这部分的设定，对于其他的分辨率，只要设置的正确就能正常截取，不过还是要手动校准的，这点比较麻烦。

而且独占全屏是看不到其他窗口的，需要窗口化才能看到OCR的浮窗提醒，如果要窗口化，那就干脆统一换成16：9的分辨率得了，也省下不少麻烦。

**Comment by yllhwa** [comment]
> 小有进展（指花了几天疯狂自学，差不多赶上了之前 @yllhwa 的进度，并做了一点点改进）
> ![rectangle_safe](https://user-images.githubusercontent.com/56406410/109408910-fec9f300-79c8-11eb-95e8-49e5d035399d.png)

哇哦，你是根据颜色区分的吗？我在hsv颜色空间没有得到很好的效果

**Comment by yllhwa** [comment]
> ![image](https://user-images.githubusercontent.com/10853091/109409125-f377c700-79ca-11eb-8b98-4d094b0b93b3.png)
> @Live4dreamCH
> 没事，新版本是开放了这部分的设定，对于其他的分辨率，只要设置的正确就能正常截取，不过还是要手动校准的，这点比较麻烦。
> 
> 而且独占全屏是看不到其他窗口的，需要窗口化才能看到OCR的浮窗提醒，如果要窗口化，那就干脆统一换成16：9的分辨率得了，也省下不少麻烦。

统一分辨率的话应该就不用识别圣遗物位置了，直接确定固定点位就好了＜（＾－＾）＞（就像楼主的做法
