### ISSUE TITLE
主词条为元素伤害加成的杯子识别生成数据错误无法导入

### ISSUE THREAD

**Issue by Kenny-Ch** [ChanIok/JumpyDumpty#3]
大佬你好，很感谢你开发的工具！
在使用过程中我发现主词条为伤害加成的杯子识别会失败，具体情况如下：
![微信图片_20210225150035](https://user-images.githubusercontent.com/54130213/109116073-ebc1e380-777a-11eb-81f8-32a7152928a0.png)
查看生成到剪贴板的结果我发现似乎是没有放到主词条中而放到了副词条中同时值也为空
```
{
            "mainTag": {},
            "normalTags": [
                {
                    "name": "iceBonus",
                    "value": ""
                },
                {
                    "name": "lifeStatic",
                    "value": 299
                },
                {
                    "name": "attackStatic",
                    "value": 19
                },
                {
                    "name": "defendStatic",
                    "value": 19
                },
                {
                    "name": "attackPercentage",
                    "value": 0.053
                }
            ],
            "position": "cup",
            "setName": "maidenBeloved",
            "detailName": "少女片刻的闲暇",
            "omit": false,
            "id": "d5fb5e3b51faf5459cd62f50f2e6107c"
        },
```
希望可以修复。

**Comment by ChanIok** [comment]
目前该功能只能抓取背包的圣遗物，使用方法说的：（**此时只需要逐个点击背包的圣遗物即可**）。
角色界面的会有异常。因为这两个界面的数据排布和位置并不一样，暂时没做这方面的处理..........
![QQ截图20210225165311](https://user-images.githubusercontent.com/10853091/109128173-339c3700-778a-11eb-93d5-cb67f9f7fb93.jpg)

**Comment by Kenny-Ch** [comment]
> 目前该功能只能抓取背包的圣遗物，使用方法说的：（**此时只需要逐个点击背包的圣遗物即可**）。
> 角色界面的会有异常。因为这两个界面的数据排布和位置并不一样，暂时没做这方面的处理..........
> ![QQ截图20210225165311](https://user-images.githubusercontent.com/10853091/109128173-339c3700-778a-11eb-93d5-cb67f9f7fb93.jpg)

噢噢噢原来如此，之前一直习惯在角色界面查看圣遗物。
因为其他圣遗物都可以正常识别我就以为是就那个有问题，没想到是我打开方式不对。
