### ISSUE TITLE
希望能够把窗户句柄设定独立出来

### ISSUE THREAD

**Issue by jason21415** [ChanIok/JumpyDumpty#4]
希望能够把窗户句柄设定独立出来
让ps端和手机模拟器也能用

ps端
窗户句柄为PS Remote Play
类名为WindowsForms10.Window.8.app.0.141b42a_r7_ad1

看挺实用的

![未命名2](https://user-images.githubusercontent.com/57126581/109153021-43764400-77a7-11eb-99b6-971d73a17e9b.png)
![未命名](https://user-images.githubusercontent.com/57126581/109153226-951ece80-77a7-11eb-861f-41ac640c5d96.png)

**Comment by ChanIok** [comment]
感谢你的建议
大概一两天内能把句柄设定和截图坐标与比例的设定完成（如果没意外的话）

**Comment by ChanIok** [comment]
已经完成这部分功能，由于这次重构的部分比较多，可能会有些问题，建议都试试。

想请问下PS Remote Play的分辨率是否固定？为多少？
可以尝试自己调整截图的位置和比例，截图设置的前两个参数控制图片大小，后两个参数控制截图的起点位置。
data文件夹下面artifact.jpg就是截取到的图片，可以通过“手动抓取”来测试得到的图片是否正确，正确的图片应该如下所示：
![artifact](https://user-images.githubusercontent.com/10853091/109383597-6bd67d80-7922-11eb-8f92-bb1147b1e624.jpg)


欢迎再次反馈，您的设置参数可以给其他PS玩家提供一个参考

**Comment by jason21415** [comment]
其實我也不知道該怎說明 
PC為W10 1440x900 縮放比100% 測試版本1.0.9beta3
PS4主機輸出電視為1080I 經PC遠端遊玩時為720P 我PC解析度為1440*900 
經過句柄截圖之後為空白內容(我用按鍵精靈的句柄截圖也是空白)
![6](https://user-images.githubusercontent.com/57126581/109391069-35175c00-7950-11eb-91ca-734d9c496107.png)
![7](https://user-images.githubusercontent.com/57126581/109391092-5aa46580-7950-11eb-8b74-9315b63caac3.png)

大小可以跟隨視窗大小改變
![1](https://user-images.githubusercontent.com/57126581/109390744-5aa36600-794e-11eb-8272-805aef2e1312.png)
![2](https://user-images.githubusercontent.com/57126581/109390750-5d05c000-794e-11eb-9a49-69aa256feff0.png)
![3](https://user-images.githubusercontent.com/57126581/109390752-5e36ed00-794e-11eb-9112-9e4c4445d0e3.png)
![4](https://user-images.githubusercontent.com/57126581/109390753-5ecf8380-794e-11eb-8997-8c1364d8a5cc.png)
設定值
![5](https://user-images.githubusercontent.com/57126581/109390905-4d3aab80-794f-11eb-84d6-e145a26f2645.png)

如果是[yllhwa](https://github.com/yllhwa/GenshinSpider)的版本我是能經過句柄截圖出可用圖片 正常使用
![8](https://user-images.githubusercontent.com/57126581/109391287-444ad980-7951-11eb-842b-2ee54acfe987.png)

地圖相關[GenshinImpact_AutoMap](https://github.com/GengGode/GenshinImpact_AutoMap)可以給你參考

如果還需要協助下面有我的聯絡方式
聯絡方式QQ1485316088或jason83228@gmail.com
