### ISSUE TITLE
快捷地图打开米有社以后由于没有退出按钮，导致卡在下载米游社app界面，无法查看大地图

### ISSUE THREAD

**Issue by violin-1** [ChanIok/JumpyDumpty#5]
![图片](https://user-images.githubusercontent.com/43943275/109248328-90e2c780-7820-11eb-9386-cae15b20c9c4.png)

**Comment by ChanIok** [comment]
第一种方法：退出程序再重启，简单暴力
建议第二种方法：关闭独立按键功能再打开，程序会销毁窗口并重新打开地图
![image](https://user-images.githubusercontent.com/10853091/109255238-95ae7800-782e-11eb-8a21-c3604a57452e.png)
