### ISSUE TITLE
用户查询命之座显示有点问题

### ISSUE THREAD

**Issue by xy9860** [ChanIok/JumpyDumpty#9]
如图
![(}LKN82KU$JOXWLP9AD$Q(E](https://user-images.githubusercontent.com/25838633/110230679-9097aa00-7f4d-11eb-9493-30d9aec056af.png)

**Comment by xy9860** [comment]
这里会重叠
![image](https://user-images.githubusercontent.com/25838633/110230712-bb81fe00-7f4d-11eb-9198-1357e840ad05.png)

**Comment by ChanIok** [comment]
感谢您的反馈
第一个的问题是直接把米游社返回的数据输出出来，他们的就是这样，因为不是特别影响理解，所以也一直没改。
第二个的问题是小的窗口可能会重叠，如果把侧边菜单收起来就不会这样

这些以后有时间都会改的

**Comment by xy9860** [comment]
我分辨率设置好了，窗口模式，但是缺提示没有权限
No permission to access data

**Comment by ChanIok** [comment]
应该是你的百度api创建时不太对
[可以参考下这个?](https://tieba.baidu.com/p/5721585653)

**Comment by xy9860** [comment]
可能是这个的问题吧，我又去勾选了一堆，现在可以了
